# Generated by Django 4.0 on 2022-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=123, upload_to='', verbose_name=type(None)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='order_name',
            field=models.CharField(max_length=20),
        ),
    ]
