# Generated by Django 4.0 on 2022-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_image_alter_client_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Comment',
            field=models.TextField(default=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
