# Generated by Django 4.0 on 2022-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_comment_alter_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default=123, max_length=12),
            preserve_default=False,
        ),
    ]
