# Generated by Django 4.0 on 2022-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_comment_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
